name: Terraform Workflow

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1

jobs:

# 1. Detect changes

  detect:
    runs-on: ubuntu-latest
    outputs:
      vpc: ${{ steps.filter.outputs.vpc }}
      eks: ${{ steps.filter.outputs.eks }}
      node: ${{ steps.filter.outputs.node }}
      first_run: ${{ steps.first.outputs.first }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect first commit
        id: first
        run: |
          if [ "$(git rev-list --count HEAD)" = "1" ]; then
            echo "first=true" >> $GITHUB_OUTPUT
          else
            echo "first=false" >> $GITHUB_OUTPUT
          fi

      - name: Detect file changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            vpc:
              - 'aws/vpc/dev/**'
              - 'modules/vpc/**'
            eks:
              - 'aws/eks/dev/**'
              - 'modules/eks/**'
            node:
              - 'aws/node-group/dev/**'
              - 'modules/node-group/**'

# ---------------------------------------
# 2. VPC
# ---------------------------------------
  vpc:
    needs: detect
    if: needs.detect.outputs.first_run == 'true' || needs.detect.outputs.vpc == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aws/vpc/dev
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform destroy
        run: terraform destroy

# ---------------------------------------
# 3. EKS
# ---------------------------------------
  eks:
    needs: [detect, vpc]
    if: |
      always() &&
      (needs.detect.outputs.first_run == 'true' || needs.detect.outputs.eks == 'true')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aws/eks/dev
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform destroy
        run: terraform destroy


# ---------------------------------------
# 4. NODE GROUP
# ---------------------------------------
  node-group:
    needs: [detect, eks]
    if: |
      always() &&
      (needs.detect.outputs.first_run == 'true' || needs.detect.outputs.node == 'true')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aws/node-group/dev
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform destroy
        run: terraform destroy
